// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rombintu/goyametricsv2/internal/agent (interfaces: Sender)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	sync "sync"

	gomock "github.com/golang/mock/gomock"
	internal "github.com/rombintu/goyametricsv2/internal/models"
)

// MockSender is a mock of Sender interface.
type MockSender struct {
	ctrl     *gomock.Controller
	recorder *MockSenderMockRecorder
}

// MockSenderMockRecorder is the mock recorder for MockSender.
type MockSenderMockRecorder struct {
	mock *MockSender
}

// NewMockSender creates a new mock instance.
func NewMockSender(ctrl *gomock.Controller) *MockSender {
	mock := &MockSender{ctrl: ctrl}
	mock.recorder = &MockSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSender) EXPECT() *MockSenderMockRecorder {
	return m.recorder
}

// PostRequestJSON mocks base method.
func (m *MockSender) PostRequestJSON(arg0 string, arg1 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostRequestJSON", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// PostRequestJSON indicates an expected call of PostRequestJSON.
func (mr *MockSenderMockRecorder) PostRequestJSON(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostRequestJSON", reflect.TypeOf((*MockSender)(nil).PostRequestJSON), arg0, arg1)
}

// RunPoll mocks base method.
func (m *MockSender) RunPoll(arg0 context.Context, arg1 *sync.WaitGroup) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RunPoll", arg0, arg1)
}

// RunPoll indicates an expected call of RunPoll.
func (mr *MockSenderMockRecorder) RunPoll(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunPoll", reflect.TypeOf((*MockSender)(nil).RunPoll), arg0, arg1)
}

// RunPollv2 mocks base method.
func (m *MockSender) RunPollv2(arg0 context.Context, arg1 *sync.WaitGroup) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RunPollv2", arg0, arg1)
}

// RunPollv2 indicates an expected call of RunPollv2.
func (mr *MockSenderMockRecorder) RunPollv2(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunPollv2", reflect.TypeOf((*MockSender)(nil).RunPollv2), arg0, arg1)
}

// RunReport mocks base method.
func (m *MockSender) RunReport(arg0 context.Context, arg1 *sync.WaitGroup) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RunReport", arg0, arg1)
}

// RunReport indicates an expected call of RunReport.
func (mr *MockSenderMockRecorder) RunReport(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunReport", reflect.TypeOf((*MockSender)(nil).RunReport), arg0, arg1)
}

// SendDataHTTP mocks base method.
func (m *MockSender) SendDataHTTP(arg0 internal.Data) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendDataHTTP", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendDataHTTP indicates an expected call of SendDataHTTP.
func (mr *MockSenderMockRecorder) SendDataHTTP(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendDataHTTP", reflect.TypeOf((*MockSender)(nil).SendDataHTTP), arg0)
}

// incPollCount mocks base method.
func (m *MockSender) incPollCount() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "incPollCount")
}

// incPollCount indicates an expected call of incPollCount.
func (mr *MockSenderMockRecorder) incPollCount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "incPollCount", reflect.TypeOf((*MockSender)(nil).incPollCount))
}

// loadMetrics mocks base method.
func (m *MockSender) loadMetrics() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "loadMetrics")
}

// loadMetrics indicates an expected call of loadMetrics.
func (mr *MockSenderMockRecorder) loadMetrics() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "loadMetrics", reflect.TypeOf((*MockSender)(nil).loadMetrics))
}
