version: '3'
tasks:
  test:
    cmds:
      - go vet -vettool=./statictest ./... > tests.log
      - go build -o cmd/server/server cmd/server/main.go >> tests.log
      - go build -o cmd/agent/agent cmd/agent/main.go >> tests.log
      - ./metricstest -test.v -agent-binary-path=./cmd/agent/agent -binary-path=./cmd/server/server -server-port=8080 -source-path=./ -file-storage-path=./store-test.json -database-dsn="host=localhost user=admin password=admin dbname=metrics sslmode=disable" >> tests.log
  build-server:
    cmds:
      - go build -o cmd/server/server cmd/server/main.go
  build-agent:
    cmds:
      - go build -o cmd/agent/agent cmd/agent/main.go
  statictest:
    cmds:
      - go vet -vettool=./statictest ./...
  gomock:
    cmds:
      - mockgen -destination=./internal/mocks/mock_storage.go -package=mocks github.com/rombintu/goyametricsv2/internal/storage Storage
  cover:
    cmds:
      - go test ./... -coverprofile profiles/cover.out && go tool cover -func=profiles/cover.out