name: Analysis code

on:
  push:

jobs:
  analyze:
    runs-on: ubuntu-latest
    container: golang:1.23

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.23

    - name: Install dependencies
      run: go mod download

    - name: Run tests
      run: go test -v ./...

    - name: Run static analysis
      run: |
        go vet ./...

    - name: Build my Analyzer
      run: go build -o staticlint cmd/staticlint/main.go 

    - name: Run static analysis (my Analyzer)
      run: |
        go vet -vettool=./staticlint ./...